[workspace]
members = ["projects/*"]
default-members = [
    "projects/from-markdown",
    "projects/from-html",
    "projects/from-org-mode",
    "projects/from-richtext",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
