[workspace]

members = ["projects/*"]
default-members = [
    "projects/panduck-core",
    "projects/panduck-pdf",
    "projects/panduck-html",
    "projects/panduck-sycamore",
]

[profile.release]
lto = true
opt-level = "s"