[package]
name = "panduck"
version = "0.2.2"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/GalAster/panduck"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
notedown_ast = "0.7.7"

anyhow = "1.0"

serde = "1.0"
serde_json="1.0"

markdown = "0.3"

html_parser = "0.4"


[dev-dependencies]

[features]
default = []


[profile.release]
lto = true
