[workspace]

members = ["projects/*"]
default-members = [
#    "projects/panduck-core",
#    "projects/panduck-cli",
#    "projects/panduck-pdf",
    "projects/panduck-html",
]

[profile.release]
lto = true
opt-level = "s"