[package]
name = "panduck-sycamore"
version = "0.7.0"
authors = ["Aster <192607617@qq.com>"]
description = "use panduck to generate pdfs"
repository = "https://github.com/oovm/panduck"
readme = "../../readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
notedown_ast = "0.13.9"

[dependencies.panduck-html]
version = "0.1.0"
path = "../panduck-html"
default-features = false

[dependencies.sycamore]
version = "0.7.0"
features = ["ssr"]

[features]
default = ["local"]
local = ["panduck-html/katex", "panduck-html/syntect"]


[dev-dependencies.panduck-core]
version = "0.1"
path = "../panduck-core"
