[package]
name = "panduck-sycamore"
version = "0.6.3"
authors = ["Aster <192607617@qq.com>"]
description = "use panduck to generate pdfs"
repository = "https://github.com/oovm/panduck"
readme = "../../readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
notedown_ast = "0.12.1"
sycamore = "0.6.3"

[dev-dependencies]
# panduck-core = {version = "0.1", path = "../panduck-core"}