[package]
name = "panduck-types"
version.workspace = true
authors.workspace = true
description = "Shared types for Panduck document conversion"
categories = ["rust-patterns"]
homepage = "https://github.com/oovm/panduck"
repository = "https://github.com/oovm/panduck"
documentation = "https://docs.rs/panduck-types"
readme = "readme.md"
license.workspace = true
edition.workspace = true
exclude = ["package.json", "tests/**"]

[lib]
doctest = false

[dependencies]
notedown-ir = { workspace = true }
url = { workspace = true }
source-map = { workspace = true }
byteorder = { workspace = true }
serde = { workspace = true }

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
